msg:
  join:
    enable: true
    text: "&eWelcome to the world, #{PLAYER}."
  join_broadcast:
    enable: false
    text: "&e#{PLAYER} is here!"
  quit_broadcast:
    enable: false
    text: "&e#{PLAYER} left."
