msg:
  join:
    enable: true
    text: "&eWelcome to the world, #{DISPLAYNAME}."
  join_broadcast:
    enable: false
    text: "&e#{DISPLAYNAME} is here!"
  quit_broadcast:
    enable: false
    text: "&e#{DISPLAYNAME} left."
