main: yy.gourlitburo.yeyajoinmessage.Main
name: YeyaJoinMessage
version: 0.0.0
api-version: 1.14
author: Zack Guard
description: Simple Spigot plugin for customizing player join and quit messages.
commands:
  yeyajoinmessage:
    aliases: [yjm]
    description: Manage YeyaJoinMessage.
    usage: "Usage: /yjm ( set <key> <msg> | ( enable | disable | show | show-raw ) <key> | reload )"
    permission: yeyajoinmessage.manage
permissions:
  yeyajoinmessage.manage:
    default: op
